### PR TITLE
Fix bug with Timepoint/Duration as parameters/returns from functions

### LINKED ISSUE #1196: Timepoint and Duration are interpreted as user defined types instead of SDK types in the WASM spec XDR
### What version are you using?

```toml
soroban-sdk = "20.0.0"
```

CLI

```
soroban 20.1.1 (deb1f7cbdc4113dbedffe981fad0dff3d5945d5c)
soroban-env 20.0.2 (81f6eb1eefd299af3e03fa0db7b20eb355b2b55f)
soroban-env interface version 85899345920
stellar-xdr 20.0.2 (a928e82943e4e93c887555fdec3b1e139ad810d2)
xdr curr (bb54e505f814386a3f45172e0b7e95b7badbe969)
```

### What did you do?

A basic Soroban contract that takes and returns `Timepoint` and `Duration` values.

```rust
#![no_std]
use soroban_sdk::{contract, contractimpl, Env, Timepoint, Duration};

#[contract]
pub struct Contract;

#[contractimpl]
impl Contract {
    pub fn read_timepoint(env: Env, time: Timepoint) -> Timepoint {
        time
    }
    pub fn read_duration(env: Env, duration: Duration) -> Duration {
        duration
    }
}
```

### What did you expect to see?

I expected to see a spec generated where types were `scSpecTypeTimepoint` and `scSpecTypeDuration`.

### What did you see instead?

These are the bindings I got after running `soroban contract bindings json --wasm`. But I do get the same results even when parsing the raw XDR straight from the WASM generated by `cargo build`, so it's definitely not CLI related.

```json
[
  {
    "type": "function",
    "doc": "",
    "name": "read_timepoint",
    "inputs": [
      {
        "doc": "",
        "name": "time",
        "value": {
          "type": "custom",
          "name": "Timepoint"
        }
      }
    ],
    "outputs": [
      {
        "type": "custom",
        "name": "Timepoint"
      }
    ]
  },
  {
    "type": "function",
    "doc": "",
    "name": "read_duration",
    "inputs": [
      {
        "doc": "",
        "name": "duration",
        "value": {
          "type": "custom",
          "name": "Duration"
        }
      }
    ],
    "outputs": [
      {
        "type": "custom",
        "name": "Duration"
      }
    ]
  }
]
```

### LINKED ISSUE #1197: Timepoint and Duration types are difficult to construct in tests
### What version are you using?

`v20.0.3`

### What did you do?

Tried to create a `Timepoint` or `Duration` using functions on the tests.

### What did you expect to see?

Some way to do that.

### What did you see instead?

No way to do that.

Other than building the XDR and converting that way:
```rust
use soroban_sdk::{xdr, IntoVal, Timepoint};

let t: Timepoint = xdr::ScVal::Timepoint(xdr::TimePoint(1)).into_val(&e);
```

### PR DESCRIPTION
**Pull request by leighmcculloch**
### What
Map contract function parameter types `Timepoint` and `Duration` to the respective spec types in the contract spec. 

### Why
They aren't being mapped today which results in them being added to the spec as custom types. This is a bug, they aren't custom types, and causes generated code to incorrectly generate clients for calling the contract.

Close #1196

### CODE REVIEW

File: soroban-sdk/src/env.rs [hunk 1]
```diff
@@ -76,7 +76,6 @@ pub mod internal {
 }
 
 pub use internal::xdr;
-pub use internal::Compare;
```
Comment (leighmcculloch) [inline soroban-sdk/src/env.rs:79]: Being removed by:
- #1199

**Review by graydon — APPROVED** [review]

**Comment by leighmcculloch** [comment]
Holding until this other change is merged:
- https://github.com/stellar/rs-soroban-sdk/issues/1195

**Comment by leighmcculloch** [comment]
Released in [v20.2.0](https://github.com/stellar/rs-soroban-sdk/releases/tag/v20.2.0).
