### PR TITLE
Generate clear error when a nameless contract argument is used 

### LINKED ISSUE #1198: Anonymous contract parameters generate unfriendly error
### What version are you using?

`v20.0.3`

### What did you do?

```rust
#![no_std]
use soroban_sdk::{contract, contractimpl};

#[contract]
pub struct Contract;

#[contractimpl]
impl Contract {
    pub fn empty(_: u64) {}
}
```

```
$ cargo build --target wasm32-unknown-unknown --release
```

### What did you expect to see?

A friendly error message telling me that I can't name parameters on contract functions `_` because that would be a nameless parameter and the contract interface/spec requires names for all parameters.

### What did you see instead?

An error that doesn't tell me where the error is. In this case I could figure out that it was the only parameter on the only function. But in a real contract with multiple functions and multiple parameters would be difficult to debug.

```
$ cargo build --target wasm32-unknown-unknown --release
error: custom attribute panicked
 --> src/lib.rs:7:1
  |
7 | #[contractimpl]
  | ^^^^^^^^^^^^^^^
  |
  = help: message: `""` is not a valid identifier
  = note: this error originates in the attribute macro `contractimpl` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no function or associated item named `empty` found for struct `Contract` in the current scope
 --> src/lib.rs:9:12
  |
5 | pub struct Contract;
  | ------------------- function or associated item `empty` not found for this struct
...
9 |     pub fn empty(_: u64) {}
  |            ^^^^^ function or associated item not found in `Contract`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `test_empty` (lib) due to 2 previous errors                                                                                                                                                        
```

### PR DESCRIPTION
**Pull request by sisuresh**
### What

Resolve #1198

What the error looks like now - 

```

error: argument not supported
 --> src/lib.rs:9:18
  |
9 |     pub fn empty(_: u64) {}
  |                  ^

error: argument not supported
 --> src/lib.rs:9:28
  |
9 |     pub fn empty(dog: u64, _: u64) {}
  |                            ^
```

### CODE REVIEW

File: soroban-sdk-macros/src/derive_client.rs [hunk 1]
```diff
@@ -170,9 +170,18 @@ pub fn derive_client_impl(crate_path: &Path, name: &str, fns: &[syn_ext::Fn]) ->
                 .map(|t| {
                     let ident = match syn_ext::fn_arg_ident(t) {
                         Ok(ident) => ident,
-                        Err(_) => {
-                            errors.push(Error::new(t.span(), "argument not supported"));
-                            format_ident!("")
+                        Err(e) => {
+                            errors.push(e);
```
Comment (leighmcculloch) [inline soroban-sdk-macros/src/derive_client.rs:174]: I think we should make the error message generated by `fn_arg_ident` a little clearer so someone knows what is allowed, by changing the error from `argument not supported` to `argument in this form is not supported, use simple named arguments only`.

File: soroban-sdk-macros/src/derive_client.rs [hunk 2]
```diff
@@ -170,9 +170,18 @@ pub fn derive_client_impl(crate_path: &Path, name: &str, fns: &[syn_ext::Fn]) ->
...
+                            if let FnArg::Typed(pat_type) = t {
+                                if let Pat::Wild(_) = *pat_type.pat.clone() {
+                                    // This will result in a clear compiler error if an underscore is used as an argument.
+                                    format_ident!("_")
+                                } else {
+                                    format_ident!("")
+                                }
+                            } else {
+                                format_ident!("")
+                            }
```
Comment (leighmcculloch) [inline soroban-sdk-macros/src/derive_client.rs:184]: There are other types of patterns that if matched against would get the `""` and cause the same panic. I think you can make the identifier `"_"` in all error cases.
```suggestion
                            format_ident!("_")
```

**Review by leighmcculloch — COMMENTED** [review]
:clap: Couple suggestions inline.

File: soroban-sdk-macros/src/derive_client.rs (hunk 1 above)
Comment (sisuresh) [reply soroban-sdk-macros/src/derive_client.rs:174]: Done

File: soroban-sdk-macros/src/derive_client.rs (hunk 2 above)
Comment (sisuresh) [reply soroban-sdk-macros/src/derive_client.rs]: I initially didn't do this because I thought it might be a confusing if the parameter name was changed to `_`, but this is still better than the existing error. I applied the suggestion.

**Review by leighmcculloch — APPROVED** [review]
